# .github/workflows/deploy_site.yml

name: 🌐 Implantação do Site (GitHub Pages)

# 1. Gatilhos: Define o que inicia o workflow
on:
  push:
    branches:
      - main # Roda automaticamente em commits para o branch principal
  
  # Permite que o workflow seja disparado manualmente pela aba 'Actions'
  workflow_dispatch:

# 2. Permissões: Essenciais para interagir com o Pages
permissions:
  contents: read # Permite o checkout do código
  pages: write # Permissão para publicar o site
  id-token: write # Permissão para autenticação segura (OIDC)

# 3. Definição do Job
jobs:
  deploy:
    name: Publicar Conteúdo Estático
    environment:
      # Liga o job ao ambiente de implantação 'github-pages'
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Obter o Código
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        
      # Passo 2 (OPCIONAL): Etapa de Build do Projeto (Comente ou remova se o site for apenas HTML/CSS/JS)
      # Se você usasse Webpack, Grunt ou Jekyll, você faria o build aqui.
      # - name: Configurar Node.js (Se necessário para build)
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Executar o Build
      #   run: npm install && npm run build # Exemplo de build

      # Passo 3: Configurar o Pages e Preparar a Implantação
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4
        
      # Passo 4: Empacotar os Arquivos para Implantação (Cria o Artefato)
      - name: Empacotar e Fazer Upload do Site
        uses: actions/upload-pages-artifact@v3
        with:
          # O caminho para a pasta que contém o seu index.html e outros assets.
          # Assumimos que está na raiz do repositório (./)
          path: './' 

      # Passo 5: Implantar o Site (Publicar)
      - name: Implantar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
