# .github/workflows/deploy_site.yml

name: 🌐 Implantação do GitHub Pages

# 1. Gatilhos: Quando este fluxo de trabalho será executado
on:
  push:
    branches:
      - main # Roda sempre que houver um push para o branch principal
  
  # Permite rodar o fluxo de trabalho manualmente
  workflow_dispatch:

# 2. Permissões
# É crucial dar permissão de leitura para o GitHub Pages Actions
permissions:
  contents: read
  pages: write # Permissão necessária para implantar no GitHub Pages
  id-token: write # Necessário para autenticação com o OIDC

# 3. Definição do Job
jobs:
  # Job de Implantação no GitHub Pages
  deploy:
    name: Implantação Estática
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL do site publicado
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Passo 2: Configurar o Node.js (necessário apenas se você for usar Webpack ou Grunt - Opcional)
      # Se você não tem etapa de build (o HTML/CSS/JS já está pronto), pode pular a instalação
      - name: Configurar Node.js (Opcional)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Passo 3: Configurar o GitHub Pages
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4
        
      # Passo 4: Fazer o build dos assets (Se você usar Grunt ou Webpack)
      # Se o seu site for puramente HTML/CSS/JS sem compilação, você pode remover este passo
      - name: Build do Projeto (Opcional - Remova se for 100% estático)
        run: |
          npm install
          # Se você usar Webpack, Grunt ou outro build, o comando estaria aqui
          # Ex: npm run build 
          echo "Nenhuma etapa de build necessária, usando arquivos estáticos."

      # Passo 5: Enviar os arquivos para o GitHub Pages
      # O action 'upload-pages-artifact' espera que os arquivos estejam prontos para serem servidos
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # A pasta que contém o index.html, ranking.html, js/, css/, etc.
          # Assumimos que a raiz do seu repositório é onde o site está
          path: './' 

      # Passo 6: Publicar o Site
      - name: Implantar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
