# .github/workflows/deploy_site.yml

name: 🌐 Implantação do GitHub Pages

# 1. Gatilhos: Quando este fluxo de trabalho será executado
on:
  push:
    branches:
      - main # Roda sempre que houver um push para o branch principal
  
  # Permite rodar o fluxo de trabalho manualmente
  workflow_dispatch:

# 2. Permissões
# O GitHub precisa dessas permissões específicas para o Pages funcionar corretamente.
permissions:
  contents: read
  pages: write 
  id-token: write 

# 3. Definição do Job
jobs:
  # Job de Implantação no GitHub Pages
  deploy:
    name: Implantação Estática
    environment:
      # O ambiente deve ser 'github-pages' para o GitHub reconhecer o deploy
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Passo 2 (Opcional): Configurar o Node.js. Mantido apenas se você for usar um build.
      - name: Configurar Node.js (Opcional)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Passo 3: Configurar o GitHub Pages
      - name: Configurar GitHub Pages
        # Este action configura os caminhos e variáveis necessários
        uses: actions/configure-pages@v4
        
      # Passo 4 (Opcional): Etapa de Build
      - name: Build do Projeto (Opcional - Remova se for 100% estático)
        run: |
          # Se o seu site for puramente HTML/CSS/JS, esta etapa não faz nada além de confirmar
          echo "Nenhuma etapa de build complexa, usando arquivos estáticos da raiz."

      # Passo 5: Enviar os arquivos para o GitHub Pages como um artefato
      # O action 'upload-pages-artifact' pega o conteúdo da pasta 'path' 
      # e o prepara para ser servido.
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # A pasta que será publicada. Assumimos a raiz do repositório
          path: './' 

      # Passo 6: Publicar o Site
      - name: Implantar no GitHub Pages
        id: deployment
        # Este action finaliza o processo e coloca o site online
        uses: actions/deploy-pages@v4
